### ISSUE TITLE
In Sidebar the button shows the namespace (of sidebar)

### ISSUE THREAD

**Issue by lizat** [rpeyron/plugin-button#10]
I am using the same code in a page and in Sidebar:

`<fs x-small>[[{ |width:7em}process:1100_manage_events:1100_manage_events|Events Overview]]  [[{ |width:7em}process:1110_manage_people:1110_manage_people|People Overview ]] [[{ |width:7em}standard_parts:emails:emails|Emails]] [[{ |width:7em}standard_parts:search:search|Search]] [[{ |width:7em}wiki_info:ebook:ebook|Create a PDF 'Book']]</fs>`

It produces this effect: https://www.screencast.com/t/X5Z5br1LL

As you can see the buttons in the side bar show the word 'Indexes' where an image might be. Indexes is the name of the namespace where this sidebar resides.

Why is this happening and is this fixable?

Thank you

**Comment by rpeyron** [comment]
Hello,

You should remove the space in the image field : `[[{|width:7em}process:1100_manage_events:1100_manage_events|Events Overview]]`

Because the space in the image field, the plugin thinks that there is an image to show, and link to the image " ". Because you are in indexes namespace, the system tries to retrieve the image link of "indexes: " and as the image is not found, it returns the namespace in plain text. That's why you are seeing it. I do not understand why it is not the same behavior on the page, it should also display the namespace of the page. Maybe your page is not in a specific namespace?

There would certainly be much to improve to this behavior, but if there is no specific reason to keep an empty space in the image field, I suggest settling to just remove spaces.

Hope this helps

**Comment by rpeyron** [comment]
Modified the regex to remove leading and trailing spaces in image field. You may update manually if you prefer keeping spaces.
