### ISSUE TITLE
Height parameter

### ISSUE THREAD

**Issue by lizat** [rpeyron/plugin-button#11]
I can'y use the height parameter. i saw the previous issue but thought the problem there was specifically with an image.. Is it possible to use the height parameter to adjust the height of the buttons?

I want all the buttons in one space to be the same dimensions, I thought a workaround might be to introduce a line break but is seems "\\" (double backslash)doesn't work with a button.

Thank you

**Comment by rpeyron** [comment]
It works quite OK for me. Example: `[[{|width:7em; height:7em;}process:1110_manage_people:1110_manage_people|People Overview ]]`   What parameters are you using?
Please consider using styles to manage all the button's style more conveniently. See https://www.dokuwiki.org/plugin:button for examples.

**Comment by lizat** [comment]
The code looks like this: [[{|width:8em; height:10px;} process:1100_manage_events:1100_manage_events|Events Overview ]]

I don't actually want it at 10px, it was just a test. I have six buttons together so one would expect to easily see the difference when I change the height of one of the. No matter what I set, it has no effect. 

I should mention that I am using Bootstrap3 template.

If I could introduce a line break I wouldn't need height. Is they a way to do this?

**Comment by rpeyron** [comment]
Hello, for the test, could you please try with 10em instead of 10px?  It is likely that the height parameter won't force content below its minimum height. 
You should also be able to insert a line break with `\\ `. Be sure to leave a space after the backslashes.  Working example: `[[{|width:17em;height: 10em;}wiki_info:ebook:ebook|Create\\ a PDF 'Book']]`.
The theme should not have an impact (and indeed I have tested ok with bootstrap3); if any doubt, you may test the CSS to include with the developer tools of your browser to test if the problem is not CSS related.
