### ISSUE TITLE
Allow use of icons plugin within buttons

### ISSUE THREAD

**Issue by fschrempf** [rpeyron/plugin-button#16]
It would be great if the [icons plugin](https://www.dokuwiki.org/plugin:icons) could be used to insert icons in a button instead of image files.

**Comment by rpeyron** [comment]
Hello, unfortunately, due to the way Dokuwiki handles syntax plugins, the use of other plugins' syntax can only be available in one portion. For button plugin this is in the title section : [[{}link |  here is the title section, you can use {{icon>home}} icons here or other dokuwiki syntax ]]. I have looked but found no simple way to make this ok in the image section. 

Please note that the author of the icons plugin has also written a bootstrap wrapper plugin that have nice looking buttons, with icon support : https://www.dokuwiki.org/plugin:bootswrapper#button  Hope this helps

**Comment by fschrempf** [comment]
@rpeyron Thanks a lot for your reply and for explaining! I really appreciate it!
