### ISSUE TITLE
plugin page documentation

### ISSUE THREAD

**Issue by turnermm** [rpeyron/plugin-button#6]
It would be useful to have all documentation on the plugin page at dokuwiki.org, instead of sending users to an external web site.  Not only would it be more convenient for the user,  but its usefulness might outlast your own interest in dokuwiki and the life of the external web site.

**Comment by rpeyron** [comment]
Hello, thanks for reporting. I added missing items in the documentation page of the plugin and removed all references of the external site (and images are now hosted on this github)

**Comment by turnermm** [comment]
I came across your plugin when one of the users of ckgedit ran into a confict, which we solved so that the button plugin can now be used in with ckgedit:
  https://github.com/turnermm/ckgedit/issues/442
All the best,
Myron

**Comment by rpeyron** [comment]
Thanks for adding button compatibility. I realize now that using a second pipe was not the smartest thing to do... 

I may suggest the use of a limit when using explode with list : with adding a limit corresponding to the number of list arguments it will prevent to loose non expected more delimiters, and thus it is more tolerant : 

by example :
`list($link_id,$linktext) = explode('|', $link[0], 2);`

instead of 
`list($link_id,$linktext) = explode('|', $link[0]);`

Thanks again for adding compatibility

**Comment by turnermm** [comment]
Please give me the line number.  Thanks.

**Comment by rpeyron** [comment]
action/save.php:212  (& :202 & :210), and virtually on any simultaneous use of list() & explode()
